packages:
  - packages/*
  - packages/static/e2e/fixture
  - packages/static/e2e/fixture-multi-entry

catalog:
  "@types/node": ^25.2.3
  react: ^19.2.4
  react-dom: ^19.2.4
  typescript: ^5.9.3
  vite: ^7.3.1

onlyBuiltDependencies:
  - esbuild
